services:
  web:
    build:
      context: PythonClient\server
      target: airsim-server
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5000:5000'
      - '41451:41541'
    extra_hosts:
      - "host.docker.internal:host-gateway"